# Generated by Django 4.1.7 on 2023-03-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('exchange', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScannerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scanner_type', models.CharField(max_length=50)),
                ('preferences', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
