# Generated by Django 4.1.7 on 2023-03-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_scanner_app', '0002_historicaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='symbol',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
